server:
  port: 8000

banner:
  location: classpath:header.txt
  
spring:
  application:
    name: company-registry
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: false
  datasource:
    initialize: false # set to true to initialize data and schema
    platform: postgres
    driver-class-name: org.postgresql.Driver
  http:
     converters:
       preferred-json-mapper: jackson
  mvc:
    static-path-pattern: /public/**/*
    throw-exception-if-no-handler-found: true
logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR
    org.apache: ERROR

